const SUPABASE_URL='https://tasoycsbzceohgjxizdp.supabase.co';
const SUPABASE_KEY='sb_publishable_ZLU-d0ZI-XT_IgabzmigkA_5vohKjLl';
const $=s=>document.querySelector(s);const state={courses:[],filtered:[],session:null,signUp:false,refreshPromise:null};
async function api(path,options={},retry=true){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${state.session?.access_token||SUPABASE_KEY}`,'Content-Type':'application/json',...(options.headers||{})}});if(r.status===401&&retry&&state.session?.refresh_token){try{await refreshAccess();return api(path,options,false)}catch{}}const data=await r.json().catch(()=>null);if(!r.ok)throw Error(data?.message||data?.error_description||data?.error||'Request failed');return r.status===204?null:data}
async function auth(path,body){const r=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error_description||data.msg||data.message||'Authentication failed');return data}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}function initials(name){return(name||'Student').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'S'}
function showAuth(signUp=state.signUp){state.signUp=signUp;$('#authModal').hidden=false;$('#authTitle').textContent=signUp?'Create your CREDENCE account':'Student Login';$('#authSubmit').textContent=signUp?'Create account':'Login';$('#nameField').classList.toggle('hidden',!signUp);$('#switchText').textContent=signUp?'Already have an account?':'New to CREDENCE?';$('#switchAuth').textContent=signUp?'Login':'Create account';let f=$('#forgotPassword');if(!f){f=document.createElement('button');f.id='forgotPassword';f.type='button';f.className='btn secondary';f.style.cssText='width:100%;margin-top:8px';f.textContent='Forgot password?';$('#authForm').appendChild(f);f.addEventListener('click',sendReset)}f.hidden=signUp;$('#authNotice').classList.add('hidden');$('#authEmail').focus()}function closeAuth(){if($('#authModal'))$('#authModal').hidden=true}
function render(){const g=$('#courseGrid');if(!g)return;g.innerHTML=state.filtered.length?state.filtered.map(c=>`<article class="course"><div class="thumb">${c.thumbnail_path?`<img src="${esc(c.thumbnail_path)}" alt="">`:'<span>CREDENCE</span>'}</div><div class="course-body"><h3>${esc(c.title)}</h3><p>${esc(c.description||'Structured learning designed for steady progress.')}</p><div class="course-foot"><strong>₹${Number(c.price_inr||0).toLocaleString('en-IN')}</strong><button class="view" data-id="${esc(c.id)}">View course</button></div></div></article>`).join(''):'<div class="empty">No courses found yet.</div>';g.querySelectorAll('.view').forEach(b=>b.onclick=()=>openCourse(b.dataset.id))}
async function loadCourses(){try{state.courses=await api('courses?select=id,title,description,thumbnail_path,price_inr,tier,published,created_at&published=eq.true&order=created_at.desc&limit=24');state.filtered=state.courses;render()}catch(e){console.error(e);if($('#courseGrid'))$('#courseGrid').innerHTML='<div class="empty">Courses could not be loaded. Please try again.</div>'}}
async function openCourse(id){const c=state.courses.find(x=>x.id===id);if(!c)return;const m=$('#courseModal'),b=$('#modalBody');m.dataset.courseId=c.id;m.hidden=false;b.innerHTML=`<h2>${esc(c.title)}</h2><p>${esc(c.description||'')}</p><div class="price">₹${Number(c.price_inr||0).toLocaleString('en-IN')}</div><p class="muted">Loading syllabus…</p>`;try{const s=await api(`course_sections?select=id,title,description,sort_order&course_id=eq.${encodeURIComponent(id)}&order=sort_order.asc`);b.innerHTML+=s.length?`<h3>Syllabus</h3>${s.map(x=>`<div class="section"><b>${esc(x.title)}</b><span>${esc(x.description||'')}</span></div>`).join('')}`:'<p class="muted">Syllabus will appear here when published.</p>'}catch(e){b.innerHTML+='<p class="muted">Syllabus is temporarily unavailable.</p>'}}
function closeCourse(){if($('#courseModal')){delete $('#courseModal').dataset.courseId;$('#courseModal').hidden=true}}async function createProfile(user,name){try{await api('profiles',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:user.id,email:user.email,full_name:name||user.user_metadata?.full_name||'',role:'student'})})}catch(e){console.warn('Profile creation deferred',e)}}
async function refreshStudent(){if(!state.session?.user?.id)return;try{const p=await api(`profiles?select=full_name,email,role,active,banned&id=eq.${state.session.user.id}&limit=1`),profile=p[0]||{},role=String(profile.role||'student').toLowerCase();if(profile.active===false||profile.banned===true)throw Error('This student account is not active.');if(!['student'].includes(role))throw Error('This account is for CREDENCE Admin. Please use the Admin login.');const name=profile.full_name||state.session.user.user_metadata?.full_name||state.session.user.email?.split('@')[0]||'Student';localStorage.setItem('credence_profile',JSON.stringify({...profile,id:state.session.user.id,email:profile.email||state.session.user.email||''}));$('#welcome').textContent=`Welcome back, ${name}`;$('#userBadge').textContent=initials(name);$('#userBadge').classList.remove('hidden');$('#loginBtn').classList.add('hidden');$('#logoutBtn').classList.remove('hidden');$('#dashboard').classList.remove('hidden');const enroll=await api(`enrollments?select=id&student_id=${state.session.user.id}&active=eq.true`);$('#enrolledCount').textContent=enroll.length;if(window.CREDENCE_LEARNING)window.CREDENCE_LEARNING.load();const cert=await api(`certificates?select=id&student_id=${state.session.user.id}`);$('#certificateCount').textContent=cert.length;const cp=enroll.length?await api(`course_progress?select=progress_percent,enrollment_id&enrollment_id=in.(${enroll.map(x=>x.id).join(',')})`):[];$('#progressCount').textContent=cp.length
