const SUPABASE_URL='https://tasoycsbzceohgjxizdp.supabase.co';
const SUPABASE_KEY='sb_publishable_ZLU-d0ZI-XT_IgabzmigkA_5vohKjLl';
const $=s=>document.querySelector(s);const state={courses:[],filtered:[],session:null,signUp:false};
async function api(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${state.session?.access_token||SUPABASE_KEY}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw Error('Request failed');return r.status===204?null:r.json()}
async function auth(path,body){const r=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error_description||data.msg||data.message||'Authentication failed');return data}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}function initials(name){return(name||'Student').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'S'}
function showAuth(signUp=state.signUp){state.signUp=signUp;$('#authModal').hidden=false;$('#authTitle').textContent=signUp?'Create your CREDENCE account':'Student Login';$('#authSubmit').textContent=signUp?'Create account':'Login';$('#nameField').classList.toggle('hidden',!signUp);$('#switchText').textContent=signUp?'Already have an account?':'New to CREDENCE?';$('#switchAuth').textContent=signUp?'Login':'Create account';$('#authNotice').classList.add('hidden');$('#authEmail').focus()}function closeAuth(){if($('#authModal'))$('#authModal').hidden=true}
function render(){const g=$('#courseGrid');if(!g)return;g.innerHTML=state.filtered.length?state.filtered.map(c=>`<article class="course"><div class="thumb">${c.thumbnail_path?`<img src="${esc(c.thumbnail_path)}" alt="">`:'<span>CREDENCE</span>'}</div><div class="course-body"><h3>${esc(c.title)}</h3><p>${esc(c.description||'Structured learning designed for steady progress.')}</p><div class="course-foot"><strong>₹${Number(c.price_inr||0).toLocaleString('en-IN')}</strong><button class="view" data-id="${esc(c.id)}">View course</button></div></div></article>`).join(''):'<div class="empty">No courses found yet.</div>';g.querySelectorAll('.view').forEach(b=>b.onclick=()=>openCourse(b.dataset.id))}
async function loadCourses(){try{state.courses=await api('courses?select=id,title,description,thumbnail_path,price_inr,tier,published,created_at&published=eq.true&order=created_at.desc&limit=24');state.filtered=state.courses;render()}catch(e){console.error(e);if($('#courseGrid'))$('#courseGrid').innerHTML='<div class="empty">Courses could not be loaded. Please try again.</div>'}}
async function openCourse(id){const c=state.courses.find(x=>x.id===id);if(!c)return;const m=$('#courseModal'),b=$('#modalBody');m.hidden=false;b.innerHTML=`<h2>${esc(c.title)}</h2><p>${esc(c.description||'')}</p><div class="price">₹${Number(c.price_inr||0).toLocaleString('en-IN')}</div><p class="muted">Loading syllabus…</p>`;try{const s=await api(`course_sections?select=id,title,description,position&course_id=eq.${encodeURIComponent(id)}&order=position.asc`);b.innerHTML+=s.length?`<h3>Syllabus</h3>${s.map(x=>`<div class="section"><b>${esc(x.title)}</b><span>${esc(x.description||'')}</span></div>`).join('')}`:'<p class="muted">Syllabus will appear here when published.</p>'}catch(e){b.innerHTML+='<p class="muted">Syllabus is temporarily unavailable.</p>'}}
function closeCourse(){if($('#courseModal'))$('#courseModal').hidden=true}async function createProfile(user,name){try{await api('profiles',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:user.id,email:user.email,full_name:name||user.user_metadata?.full_name||''})})}catch(e){console.warn('Profile creation deferred',e)}}
async function refreshStudent(){if(!state.session)return;try{const p=await api(`profiles?select=full_name,email,role&id=eq.${state.session.user.id}&limit=1`),profile=p[0]||{},name=profile.full_name||state.session.user.user_metadata?.full_name||state.session.user.email?.split('@')[0]||'Student';$('#welcome').textContent=`Welcome back, ${name}`;$('#userBadge').textContent=initials(name);$('#userBadge').classList.remove('hidden');$('#loginBtn').classList.add('hidden');$('#logoutBtn').classList.remove('hidden');$('#dashboard').classList.remove('hidden');const enroll=await api(`enrollments?select=id&student_id=eq.${state.session.user.id}`);$('#enrolledCount').textContent=enroll.length;if(window.CREDENCE_LEARNING)window.CREDENCE_LEARNING.load();const cert=await api(`certificates?select=id&student_id=eq.${state.session.user.id}`);$('#certificateCount').textContent=cert.length;const cp=await api(`course_progress?select=progress_percent&student_id=eq.${state.session.user.id}`);$('#progressCount').textContent=cp.length?Math.round(cp.reduce((a,x)=>a+Number(x.progress_percent||0),0)/cp.length)+'%':'0%'}catch(e){console.warn('Student dashboard load',e)}}
function saveSession(data){state.session=data;localStorage.setItem('credence_session',JSON.stringify(data))}function loadSession(){try{const x=JSON.parse(localStorage.getItem('credence_session')||'null');if(x?.access_token&&x?.user)state.session=x}catch(e){localStorage.removeItem('credence_session')}}
async function logout(){state.session=null;localStorage.removeItem('credence_session');$('#dashboard').classList.add('hidden');$('#userBadge').classList.add('hidden');$('#loginBtn').classList.remove('hidden');$('#logoutBtn').classList.add('hidden');if($('#myLearningGrid'))$('#myLearningGrid').innerHTML='<div class="empty">Log in to see your enrolled courses.</div>'}
async function submitAuth(e){e.preventDefault();const notice=$('#authNotice');notice.classList.add('hidden');const email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();$('#authSubmit').disabled=true;try{if(state.signUp){const d=await auth('signup',{email,password,data:{full_name:name}});if(d.access_token){saveSession(d);await createProfile(d.user,name);closeAuth();await refreshStudent()}else{notice.textContent='Account created. Check your email to confirm your account, then log in.';notice.classList.remove('hidden')}}else{const d=await auth('token?grant_type=password',{email,password});saveSession(d);await createProfile(d.user,d.user.user_metadata?.full_name);closeAuth();await refreshStudent()}}catch(err){notice.textContent=err.message;notice.classList.remove('hidden')}finally{$('#authSubmit').disabled=false}}
document.addEventListener('DOMContentLoaded',async()=>{loadSession();loadCourses();if(state.session)await refreshStudent();$('#loginBtn')?.addEventListener('click',()=>showAuth(false));$('#heroLogin')?.addEventListener('click',()=>showAuth(true));$('#logoutBtn')?.addEventListener('click',logout);$('#closeAuth')?.addEventListener('click',closeAuth);$('#switchAuth')?.addEventListener('click',()=>showAuth(!state.signUp));$('#authForm')?.addEventListener('submit',submitAuth);$('#search')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();state.filtered=state.courses.filter(c=>`${c.title} ${c.description||''}`.toLowerCase().includes(q));render()});$('#closeModal')?.addEventListener('click',closeCourse);$('#courseModal')?.addEventListener('click',e=>{if(e.target.id==='courseModal')closeCourse()});$('#authModal')?.addEventListener('click',e=>{if(e.target.id==='authModal')closeAuth()})});

document.addEventListener('DOMContentLoaded',()=>{const b=document.createElement('a');b.href='profile.html';b.textContent='Profile & Settings';b.className='btn secondary';b.id='profileLink';const host=document.querySelector('header .topline');if(host&&!document.getElementById('profileLink'))host.insertBefore(b,host.firstChild);});