(() => {
const URL='https://tasoycsbzceohgjxizdp.supabase.co';
const KEY='sb_publishable_ZLU-d0ZI-XT_IgabzmigkA_5vohKjLl';
const ENDPOINT=`${URL}/functions/v1/credence-checkout`;
const token=()=>{try{return JSON.parse(localStorage.getItem('credence_session')||'null')?.access_token||''}catch{return ''}};
const api=async(body)=>{const t=token();const r=await fetch(ENDPOINT,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok&&d.status!=='payment_setup_required')throw Error(d.error||'Checkout failed');return d};
function notice(text,good=false){const n=document.getElementById('checkoutNotice');if(n){n.innerHTML=text;n.classList.remove('hidden');n.style.borderColor=good?'#b7e4c7':'#ffd6a5';n.style.background=good?'#f0fff4':'#fff8ed'}}
async function loadRazorpay(){if(window.Razorpay)return true;return await new Promise(resolve=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
async function checkout(courseId,btn){const t=token();if(!t){document.getElementById('loginBtn')?.click();return}if(btn){btn.disabled=true;btn.textContent='Preparing…'}try{
 const d=await api({action:'create_order',course_id:courseId});
 if(d.status==='already_enrolled'||d.status==='enrolled'){document.getElementById('courseModal').hidden=true;window.CREDENCE_LEARNING?.load();document.getElementById('dashboard')?.classList.remove('hidden');document.getElementById('myLearningGrid')?.scrollIntoView({behavior:'smooth',block:'start'});alert('You are enrolled. Start learning! 🎓');return}
 if(d.status==='payment_setup_required'){notice('<b>Razorpay Test Mode is almost ready.</b><br>Add the Razorpay Test keys privately to Supabase, then this Buy button will open the secure UPI checkout.');return}
 if(d.status!=='order_created')throw Error(d.error||'Unable to create payment order');
 const ready=await loadRazorpay();if(!ready)throw Error('Payment checkout could not load. Check your internet connection and try again.');
 notice('<b>Secure checkout ready.</b><br>Choose UPI in Razorpay Checkout. Test Mode uses simulated payments; no real money is charged.');
 const options={key:d.key_id,amount:d.amount,currency:d.currency||'INR',name:'CREDENCE',description:d.course?.title||'CREDENCE Course',order_id:d.razorpay_order_id,prefill:{name:(JSON.parse(localStorage.getItem('credence_profile')||'null')?.full_name)||'',email:(JSON.parse(localStorage.getItem('credence_profile')||'null')?.email)||''},theme:{color:'#08783f'},handler:async response=>{try{notice('<b>Verifying payment…</b><br>Please wait. Course access is granted only after server verification.');const v=await api({action:'verify_payment',order_id:d.order_id,razorpay_order_id:response.razorpay_order_id,razorpay_payment_id:response.razorpay_payment_id,razorpay_signature:response.razorpay_signature});if(v.status!=='enrolled')throw Error(v.error||'Payment was not verified');document.getElementById('courseModal').hidden=true;window.CREDENCE_LEARNING?.load();document.getElementById('dashboard')?.classList.remove('hidden');document.getElementById('myLearningGrid')?.scrollIntoView({behavior:'smooth',block:'start'});alert('Payment verified — you are enrolled! 🎓');}catch(e){notice(`<b>Payment received but verification needs attention.</b><br>${e.message||'Please contact CREDENCE support.'}`)}}};
 const rzp=new Razorpay(options);rzp.on('payment.failed',r=>{notice(`<b>Payment failed.</b><br>${r?.error?.description||'Please try again.'}`)});rzp.open();
 }catch(e){notice(`<b>Checkout failed.</b><br>${e.message||'Please try again.'}`)}finally{if(btn){btn.disabled=false;btn.textContent='Buy / Enroll'}}}
async function inject(){const modal=document.getElementById('courseModal'),body=document.getElementById('modalBody');if(!modal||modal.hidden||!body||document.getElementById('credenceBuy'))return;const title=body.querySelector('h2')?.textContent?.trim();if(!title)return;const r=await fetch(`${URL}/rest/v1/courses?select=id,title&published=eq.true&title=eq.${encodeURIComponent(title)}&limit=1`,{headers:{apikey:KEY}});if(!r.ok)return;const rows=await r.json();if(!rows[0]||document.getElementById('credenceBuy'))return;const wrap=document.createElement('div');wrap.className='actions';wrap.innerHTML='<button id="credenceBuy">Buy / Enroll</button><div id="checkoutNotice" class="notice hidden"></div>';body.insertBefore(wrap,body.children[1]||body.firstChild);document.getElementById('credenceBuy').onclick=()=>checkout(rows[0].id,document.getElementById('credenceBuy'))}
window.CREDENCE_CHECKOUT={checkout};new MutationObserver(()=>inject()).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['hidden']});document.addEventListener('DOMContentLoaded',inject);
})();