(function(){
const PRIMARY_UID='aBYdbFwbsTUbpmYtoNurxyu3Roj2';
let firestorePromise;
const firestore=()=>firestorePromise||(firestorePromise=import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js'));
const firebase=()=>window.credenceFirebase;
const isSuper=async()=>{const f=firebase(),u=f?.auth?.currentUser;if(!f||!u)return false;if(u.uid===PRIMARY_UID)return true;try{const x=await firestore(),s=await x.getDoc(x.doc(f.db,'superAdmins',u.uid));return s.exists()&&s.data().active===true}catch(e){return false}};
const toast=m=>{let t=document.getElementById('ceFixToast');if(!t){t=document.createElement('div');t.id='ceFixToast';t.style='position:fixed;right:18px;bottom:82px;background:#17352a;color:#fff;padding:12px 15px;border-radius:10px;z-index:9999;font-weight:700';document.body.appendChild(t)}t.textContent=m;t.style.display='block';clearTimeout(t._x);t._x=setTimeout(()=>t.style.display='none',2500)};
async function toggleAdmin(id,active){if(!(await isSuper()))return toast('Super Admin permission required.');if(!id||id===PRIMARY_UID)return;try{const x=await firestore(),f=firebase();await x.updateDoc(x.doc(f.db,'superAdmins',id),{active,updatedAt:x.serverTimestamp(),updatedBy:f.auth.currentUser.uid});toast(active?'Super Admin enabled.':'Super Admin disabled.');if(window.credenceOpenSuperAdmins)window.credenceOpenSuperAdmins()}catch(e){toast('Could not update admin: '+e.message)}}
async function toggleStudent(id,active){if(!(await isSuper()))return toast('Super Admin permission required.');try{const x=await firestore(),f=firebase();await x.updateDoc(x.doc(f.db,'students',id),{active,updatedAt:x.serverTimestamp()});toast(active?'Student enabled.':'Student disabled.');if(window.credenceOpenStudents)window.credenceOpenStudents()}catch(e){toast('Could not update student: '+e.message)}}
async function removeStudent(id,name){if(!(await isSuper()))return toast('Super Admin permission required.');if(!confirm('Remove '+name+' permanently? This cannot be undone.'))return;try{const x=await firestore(),f=firebase();await x.deleteDoc(x.doc(f.db,'students',id));toast('Student removed.');if(window.credenceOpenStudents)window.credenceOpenStudents()}catch(e){toast('Could not remove student: '+e.message)}}
function patchAdmins(){const list=document.getElementById('ceList');if(!list)return;list.querySelectorAll('button[data-admin]').forEach(b=>{const row=b.closest('.row');const disabled=!!row?.querySelector('.badge.cancel');b.textContent=disabled?'Enable':'Disable';b.className='btn '+(disabled?'alt':'danger');b.onclick=()=>toggleAdmin(b.dataset.admin,!disabled)})}
function patchStudents(){const body=document.getElementById('ceStudentRows');if(!body)return;body.querySelectorAll('tr').forEach(r=>{const edit=r.querySelector('[data-edit-student]');if(!edit)return;const id=edit.dataset.editStudent;const status=r.querySelector('.badge');const disabled=!!r.querySelector('.badge.cancel');let b=r.querySelector('[data-toggle-student]');if(!b){b=document.createElement('button');b.dataset.toggleStudent=id;b.className='btn';edit.parentElement.appendChild(b)}b.textContent=disabled?'Enable':'Disable';b.className='btn '+(disabled?'alt':'danger');b.onclick=()=>toggleStudent(id,!disabled);if(!r.querySelector('[data-remove-student]')){const rm=document.createElement('button');rm.dataset.removeStudent=id;rm.className='btn danger';rm.textContent='Remove';rm.style.marginLeft='4px';rm.onclick=()=>removeStudent(id,r.querySelector('td b')?.textContent||'this student');edit.parentElement.appendChild(rm)}})}
function patchCustomize(){document.querySelectorAll('.mobilebar button').forEach(b=>{if(/customize/i.test((b.textContent||''))&&!b.dataset.ceCustomize){b.dataset.ceCustomize='1';b.onclick=e=>{e.preventDefault();e.stopPropagation();const q=[...document.querySelectorAll('button')].find(x=>/customize app/i.test((x.textContent||'').trim()));if(q&&q!==b){q.click();return}const v=[...document.querySelectorAll('.view')].find(x=>/custom/i.test(x.textContent||''));if(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));v.classList.add('active')}}}})}
function patch(){patchAdmins();patchStudents();patchCustomize()}
document.addEventListener('click',e=>{const a=e.target.closest?.('button[data-admin]');if(a){e.preventDefault();e.stopImmediatePropagation();const row=a.closest('.row');toggleAdmin(a.dataset.admin,!row?.querySelector('.badge.cancel'));return}const s=e.target.closest?.('button[data-toggle-student]');if(s){e.preventDefault();e.stopImmediatePropagation();const r=s.closest('tr');toggleStudent(s.dataset.toggleStudent,!r?.querySelector('.badge.cancel'));return}},true);
patch();new MutationObserver(patch).observe(document.body,{childList:true,subtree:true,characterData:true});setInterval(patch,500);
})();
