(function(){
  const PRIMARY_UID='aBYdbFwbsTUbpmYtoNurxyu3Roj2';
  const wait=()=>new Promise(resolve=>{const t=setInterval(()=>{if(window.credenceFirebase){clearInterval(t);resolve(window.credenceFirebase)}},50);setTimeout(()=>{clearInterval(t);resolve(window.credenceFirebase)},10000)});
  const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  async function load(){
    const f=await wait();if(!f)return;
    const {db,auth}=f;
    const {collection,getDoc,getDocs,doc,setDoc,updateDoc,addDoc,onSnapshot,serverTimestamp}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js');
    const {getApp,initializeApp}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js');
    const {getAuth,createUserWithEmailAndPassword,signOut}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js');
    let secondaryAuth;
    const toast=msg=>{let x=document.getElementById('ceToast');if(!x){x=document.createElement('div');x.id='ceToast';x.style='position:fixed;right:18px;bottom:82px;background:#17352a;color:#fff;padding:12px 15px;border-radius:10px;z-index:9999;font-weight:700';document.body.appendChild(x)}x.textContent=msg;x.style.display='block';setTimeout(()=>x.style.display='none',2500)};
    const isSuper=async()=>{const u=auth.currentUser;if(!u)return false;if(u.uid===PRIMARY_UID)return true;try{const s=await getDoc(doc(db,'superAdmins',u.uid));return s.exists()&&s.data().active!==false}catch(e){return false}};

    const openAdmins=async()=>{if(!(await isSuper()))return toast('Super Admin permission required.');let v=document.getElementById('ceAdminView');if(v){v.style.display='block';return renderAdmins()}v=document.createElement('div');v.id='ceAdminView';v.style='position:fixed;inset:0;background:#f3f7f4;z-index:500;overflow:auto;padding:18px';v.innerHTML='<div style="max-width:900px;margin:auto"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px"><div><h1 style="margin:0;color:#17352a">Super Admin Management</h1><div style="color:#718078;margin-top:4px">Add trusted administrators who can manage CREDENCE.</div></div><button id="ceClose" class="btn">Back</button></div><div class="card" style="margin-bottom:16px"><h2>Add Super Admin</h2><div class="formgrid"><div class="field"><label>Name</label><input id="ceName" placeholder="Full name"></div><div class="field"><label>Email</label><input id="ceEmail" type="email" placeholder="admin@example.com"></div><div class="field"><label>Temporary password</label><input id="cePass" type="password" placeholder="At least 6 characters"></div></div><button id="ceAdd" class="btn" style="margin-top:14px">+ Add Super Admin</button><div id="ceMsg" class="muted" style="margin-top:10px"></div></div><div class="card"><h2>Super Admins</h2><div id="ceList">Loading...</div></div></div>';document.body.appendChild(v);document.getElementById('ceClose').onclick=()=>v.remove();document.getElementById('ceAdd').onclick=addAdmin;renderAdmins()};
    async function renderAdmins(){const el=document.getElementById('ceList');if(!el)return;el.textContent='Loading...';try{const snap=await getDocs(collection(db,'superAdmins'));const rows=[];snap.forEach(s=>rows.push({id:s.id,...s.data()}));if(!rows.some(x=>x.uid===PRIMARY_UID||x.id===PRIMARY_UID))rows.unshift({uid:PRIMARY_UID,name:'Primary Super Admin',email:'Primary account',active:true,primary:true});el.innerHTML=rows.map(x=>'<div class="row"><div class="grow"><b>'+esc(x.name||'Super Admin')+'</b><div class="muted">'+esc(x.email||'')+'</div></div><span class="badge '+(x.active===false?'cancel':'')+'">'+(x.active===false?'Disabled':'Active')+'</span>'+(x.primary?'':'<button class="btn danger" data-admin="'+esc(x.uid||x.id)+'">Disable</button>')+'</div>').join('');el.querySelectorAll('[data-admin]').forEach(b=>b.onclick=()=>disableAdmin(b.dataset.admin))}catch(e){el.textContent='Could not load admins: '+e.message}};
    async function addAdmin(){const name=document.getElementById('ceName').value.trim(),email=document.getElementById('ceEmail').value.trim().toLowerCase(),pass=document.getElementById('cePass').value,msg=document.getElementById('ceMsg');if(!name||!email||pass.length<6){msg.textContent='Enter name, valid email and password (6+ characters).';return}if(!(await isSuper())){msg.textContent='Not authorized.';return}const btn=document.getElementById('ceAdd');btn.disabled=true;msg.textContent='Creating account...';try{const primaryApp=getApp();const secondaryApp=initializeApp(primaryApp.options,'credence-admin-secondary');secondaryAuth=getAuth(secondaryApp);const cred=await createUserWithEmailAndPassword(secondaryAuth,email,pass);await setDoc(doc(db,'superAdmins',cred.user.uid),{uid:cred.user.uid,name,email,active:true,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});await signOut(secondaryAuth);msg.textContent='Super Admin created successfully.';document.getElementById('ceName').value='';document.getElementById('ceEmail').value='';document.getElementById('cePass').value='';renderAdmins()}catch(e){msg.textContent=e.code?e.code+': '+e.message:e.message}finally{btn.disabled=false}};
    async function disableAdmin(uid){if(!(await isSuper()))return toast('Not authorized.');if(uid===PRIMARY_UID)return toast('The primary Super Admin cannot be disabled.');if(!confirm('Disable this Super Admin?'))return;try{await updateDoc(doc(db,'superAdmins',uid),{active:false,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid});toast('Super Admin disabled.');renderAdmins()}catch(e){toast('Could not update admin: '+e.message)}}

    let stopStudents=null;
    const closeStudents=()=>{if(stopStudents){stopStudents();stopStudents=null}const v=document.getElementById('ceStudentView');if(v)v.remove()};
    const openStudents=async()=>{
      if(!(await isSuper()))return toast('Super Admin permission required.');
      let v=document.getElementById('ceStudentView');
      if(v){v.style.display='block';return renderStudents();}
      v=document.createElement('div');v.id='ceStudentView';v.style='position:fixed;inset:0;background:#f3f7f4;z-index:490;overflow:auto;padding:18px';
      v.innerHTML='<div style="max-width:1050px;margin:auto"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px"><div><h1 style="margin:0;color:#17352a">Student Management</h1><div style="color:#718078;margin-top:4px">Manage CREDENCE students in real time.</div></div><button id="ceStudentClose" class="btn">Back</button></div><div class="card" style="margin-bottom:16px"><h2 id="ceStudentFormTitle">Add Student</h2><div class="formgrid"><div class="field"><label>Full name</label><input id="ceStudentName" placeholder="Student name"></div><div class="field"><label>Roll number</label><input id="ceStudentRoll" placeholder="Roll number"></div><div class="field"><label>Class</label><input id="ceStudentClass" placeholder="Class / section"></div><div class="field"><label>Phone</label><input id="ceStudentPhone" type="tel" placeholder="Phone number"></div><div class="field"><label>Email</label><input id="ceStudentEmail" type="email" placeholder="student@example.com"></div><div class="field"><label>Status</label><select id="ceStudentActive"><option value="true">Active</option><option value="false">Disabled</option></select></div></div><div class="actions" style="margin-top:14px"><button id="ceStudentSave" class="btn">+ Add Student</button><button id="ceStudentCancel" class="btn alt" style="display:none">Cancel edit</button></div><div id="ceStudentMsg" class="muted" style="margin-top:10px"></div></div><div class="card"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><h2 style="margin:0">Students</h2><input id="ceStudentSearch" class="search" placeholder="Search name, roll, class, phone or email"></div><div id="ceStudentCount" class="muted" style="margin:10px 0">Loading students...</div><div class="tablewrap"><table class="table"><thead><tr><th>Name</th><th>Roll</th><th>Class</th><th>Phone</th><th>Email</th><th>Status</th><th>Actions</th></tr></thead><tbody id="ceStudentRows"><tr><td colspan="7">Loading...</td></tr></tbody></table></div></div></div>';
      document.body.appendChild(v);
      document.getElementById('ceStudentClose').onclick=closeStudents;
      document.getElementById('ceStudentCancel').onclick=resetStudentForm;
      document.getElementById('ceStudentSave').onclick=saveStudent;
      document.getElementById('ceStudentSearch').oninput=renderStudents;
      renderStudents();
      if(stopStudents)stopStudents();
      stopStudents=onSnapshot(collection(db,'students'),snap=>{window.credenceStudents=[];snap.forEach(s=>window.credenceStudents.push({id:s.id,...s.data()}));renderStudents()},e=>{const msg=document.getElementById('ceStudentMsg');if(msg)msg.textContent='Could not load students: '+e.message});
    };
    function renderStudents(){const rowsEl=document.getElementById('ceStudentRows');if(!rowsEl)return;const all=window.credenceStudents||[];const q=(document.getElementById('ceStudentSearch')?.value||'').trim().toLowerCase();const rows=all.filter(x=>!q||[x.name,x.rollNo,x.className,x.phone,x.email].some(v=>String(v??'').toLowerCase().includes(q)));const count=document.getElementById('ceStudentCount');if(count)count.textContent=rows.length+' of '+all.length+' students';if(!rows.length){rowsEl.innerHTML='<tr><td colspan="7" class="muted">No students found.</td></tr>';return}rowsEl.innerHTML=rows.map(x=>'<tr><td><b>'+esc(x.name||'')+'</b></td><td>'+esc(x.rollNo||'')+'</td><td>'+esc(x.className||'')+'</td><td>'+esc(x.phone||'')+'</td><td>'+esc(x.email||'')+'</td><td><span class="badge '+(x.active===false?'cancel':'')+'">'+(x.active===false?'Disabled':'Active')+'</span></td><td><div class="actions"><button class="btn alt" data-edit-student="'+esc(x.id)+'">Edit</button><button class="btn '+(x.active===false?'':'danger')+'" data-toggle-student="'+esc(x.id)+'">'+(x.active===false?'Activate':'Disable')+'</button></div></td></tr>').join('');rowsEl.querySelectorAll('[data-edit-student]').forEach(b=>b.onclick=()=>editStudent(b.dataset.editStudent));rowsEl.querySelectorAll('[data-toggle-student]').forEach(b=>b.onclick=()=>toggleStudent(b.dataset.toggleStudent))}
    async function saveStudent(){const msg=document.getElementById('ceStudentMsg'),id=document.getElementById('ceStudentSave').dataset.editId||'';const data={name:document.getElementById('ceStudentName').value.trim(),rollNo:document.getElementById('ceStudentRoll').value.trim(),className:document.getElementById('ceStudentClass').value.trim(),phone:document.getElementById('ceStudentPhone').value.trim(),email:document.getElementById('ceStudentEmail').value.trim().toLowerCase(),active:document.getElementById('ceStudentActive').value==='true'};if(!data.name||!data.rollNo||!data.className||!data.phone||!data.email){msg.textContent='Please fill all student fields.';return}if(!(await isSuper())){msg.textContent='Not authorized.';return}const btn=document.getElementById('ceStudentSave');btn.disabled=true;msg.textContent=id?'Saving changes...':'Adding student...';try{if(id){await updateDoc(doc(db,'students',id),{...data,updatedAt:serverTimestamp()});msg.textContent='Student updated successfully.'}else{await addDoc(collection(db,'students'),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});msg.textContent='Student added successfully.'}resetStudentForm(false)}catch(e){msg.textContent=e.code?e.code+': '+e.message:e.message}finally{btn.disabled=false}}
    function editStudent(id){const x=(window.credenceStudents||[]).find(s=>s.id===id);if(!x)return;document.getElementById('ceStudentName').value=x.name||'';document.getElementById('ceStudentRoll').value=x.rollNo||'';document.getElementById('ceStudentClass').value=x.className||'';document.getElementById('ceStudentPhone').value=x.phone||'';document.getElementById('ceStudentEmail').value=x.email||'';document.getElementById('ceStudentActive').value=x.active===false?'false':'true';const b=document.getElementById('ceStudentSave');b.dataset.editId=id;b.textContent='Save Changes';document.getElementById('ceStudentCancel').style.display='inline-block';document.getElementById('ceStudentFormTitle').textContent='Edit Student';window.scrollTo({top:0,behavior:'smooth'})}
    function resetStudentForm(clearMsg=true){['ceStudentName','ceStudentRoll','ceStudentClass','ceStudentPhone','ceStudentEmail'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});const s=document.getElementById('ceStudentActive');if(s)s.value='true';const b=document.getElementById('ceStudentSave');if(b){delete b.dataset.editId;b.textContent='+ Add Student'}const c=document.getElementById('ceStudentCancel');if(c)c.style.display='none';const t=document.getElementById('ceStudentFormTitle');if(t)t.textContent='Add Student';if(clearMsg){const m=document.getElementById('ceStudentMsg');if(m)m.textContent=''}}
    async function toggleStudent(id){if(!(await isSuper()))return toast('Not authorized.');const x=(window.credenceStudents||[]).find(s=>s.id===id);if(!x)return;try{await updateDoc(doc(db,'students',id),{active:x.active===false,updatedAt:serverTimestamp()});toast(x.active===false?'Student activated.':'Student disabled.')}catch(e){toast('Could not update student: '+e.message)}}

    const addButton=()=>{const navs=[...document.querySelectorAll('.nav button,.mobilebar button')];navs.forEach(b=>{if(/customize/i.test(b.textContent)&&!document.getElementById('ceAdminBtn')){const n=b.cloneNode(true);n.id='ceAdminBtn';n.innerHTML='<span>🛡️</span> Super Admins';n.onclick=openAdmins;b.parentElement.insertBefore(n,b)}if(/students/i.test(b.textContent)&&!document.getElementById('ceStudentBtn')){b.onclick=openStudents;b.id='ceStudentBtn'}});const qa=[...document.querySelectorAll('button')].find(b=>/customize app/i.test(b.textContent));if(qa&&!document.getElementById('ceQuickAdmin')){const n=qa.cloneNode(true);n.id='ceQuickAdmin';n.textContent='🛡️ Super Admins';n.onclick=openAdmins;qa.parentElement.appendChild(n)}const qs=[...document.querySelectorAll('button')].find(b=>/^\+?\s*student$/i.test(b.textContent.trim()));if(qs&&!document.getElementById('ceQuickStudent')){qs.onclick=openStudents;qs.id='ceQuickStudent'}};
    window.credenceOpenSuperAdmins=openAdmins;window.credenceOpenStudents=openStudents;addButton();
  }
  load();
})();
