(function(){
  const PRIMARY_UID='aBYdbFwbsTUbpmYtoNurxyu3Roj2';
  const wait=()=>new Promise(resolve=>{const t=setInterval(()=>{if(window.credenceFirebase){clearInterval(t);resolve(window.credenceFirebase)}},50);setTimeout(()=>{clearInterval(t);resolve(window.credenceFirebase)},10000)});
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  async function load(){
    const f=await wait();if(!f)return;
    const {db,auth}=f;
    const {collection,getDoc,getDocs,doc,setDoc,updateDoc,serverTimestamp}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js');
    const {getApp,initializeApp}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js');
    const {getAuth,createUserWithEmailAndPassword,signOut}=await import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js');
    let secondaryAuth;
    const toast=msg=>{let x=document.getElementById('ceToast');if(!x){x=document.createElement('div');x.id='ceToast';x.style='position:fixed;right:18px;bottom:82px;background:#17352a;color:#fff;padding:12px 15px;border-radius:10px;z-index:9999;font-weight:700';document.body.appendChild(x)}x.textContent=msg;x.style.display='block';setTimeout(()=>x.style.display='none',2500)};
    const isSuper=async()=>{const u=auth.currentUser;if(!u)return false;if(u.uid===PRIMARY_UID)return true;try{const s=await getDoc(doc(db,'superAdmins',u.uid));return s.exists()&&s.data().active!==false}catch(e){return false}};
    const openAdmins=async()=>{if(!(await isSuper()))return toast('Super Admin permission required.');let v=document.getElementById('ceAdminView');if(v){v.style.display='block';return renderAdmins()}v=document.createElement('div');v.id='ceAdminView';v.style='position:fixed;inset:0;background:#f3f7f4;z-index:500;overflow:auto;padding:18px';v.innerHTML='<div style="max-width:900px;margin:auto"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px"><div><h1 style="margin:0;color:#17352a">Super Admin Management</h1><div style="color:#718078;margin-top:4px">Add trusted administrators who can manage CREDENCE.</div></div><button id="ceClose" class="btn">Back</button></div><div class="card" style="margin-bottom:16px"><h2>Add Super Admin</h2><div class="formgrid"><div class="field"><label>Name</label><input id="ceName" placeholder="Full name"></div><div class="field"><label>Email</label><input id="ceEmail" type="email" placeholder="admin@example.com"></div><div class="field"><label>Temporary password</label><input id="cePass" type="password" placeholder="At least 6 characters"></div></div><button id="ceAdd" class="btn" style="margin-top:14px">+ Add Super Admin</button><div id="ceMsg" class="muted" style="margin-top:10px"></div></div><div class="card"><h2>Super Admins</h2><div id="ceList">Loading...</div></div></div>';document.body.appendChild(v);document.getElementById('ceClose').onclick=()=>v.remove();document.getElementById('ceAdd').onclick=addAdmin;renderAdmins()};
    async function renderAdmins(){const el=document.getElementById('ceList');if(!el)return;el.textContent='Loading...';try{const snap=await getDocs(collection(db,'superAdmins'));const rows=[];snap.forEach(s=>rows.push({id:s.id,...s.data()}));if(!rows.some(x=>x.uid===PRIMARY_UID||x.id===PRIMARY_UID))rows.unshift({uid:PRIMARY_UID,name:'Primary Super Admin',email:'Primary account',active:true,primary:true});el.innerHTML=rows.map(x=>'<div class="row"><div class="grow"><b>'+esc(x.name||'Super Admin')+'</b><div class="muted">'+esc(x.email||'')+'</div></div><span class="badge '+(x.active===false?'cancel':'')+'">'+(x.active===false?'Disabled':'Active')+'</span>'+(x.primary?'':'<button class="btn danger" data-admin="'+esc(x.uid||x.id)+'">Disable</button>')+'</div>').join('');el.querySelectorAll('[data-admin]').forEach(b=>b.onclick=()=>disableAdmin(b.dataset.admin))}catch(e){el.textContent='Could not load admins: '+e.message}};
    async function addAdmin(){const name=document.getElementById('ceName').value.trim(),email=document.getElementById('ceEmail').value.trim().toLowerCase(),pass=document.getElementById('cePass').value,msg=document.getElementById('ceMsg');if(!name||!email||pass.length<6){msg.textContent='Enter name, valid email and password (6+ characters).';return}if(!(await isSuper())){msg.textContent='Not authorized.';return}const btn=document.getElementById('ceAdd');btn.disabled=true;msg.textContent='Creating account...';try{const primaryApp=getApp();const secondaryApp=initializeApp(primaryApp.options,'credence-admin-secondary');secondaryAuth=getAuth(secondaryApp);const cred=await createUserWithEmailAndPassword(secondaryAuth,email,pass);await setDoc(doc(db,'superAdmins',cred.user.uid),{uid:cred.user.uid,name,email,active:true,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});await signOut(secondaryAuth);msg.textContent='Super Admin created successfully.';document.getElementById('ceName').value='';document.getElementById('ceEmail').value='';document.getElementById('cePass').value='';renderAdmins()}catch(e){msg.textContent=e.code?e.code+': '+e.message:e.message}finally{btn.disabled=false}};
    async function disableAdmin(uid){if(!(await isSuper()))return toast('Not authorized.');if(uid===PRIMARY_UID)return toast('The primary Super Admin cannot be disabled.');if(!confirm('Disable this Super Admin?'))return;try{await updateDoc(doc(db,'superAdmins',uid),{active:false,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid});toast('Super Admin disabled.');renderAdmins()}catch(e){toast('Could not update admin: '+e.message)}}
    const addButton=()=>{const navs=[...document.querySelectorAll('.nav button,.mobilebar button')];navs.forEach(b=>{if(/customize/i.test(b.textContent)&&!document.getElementById('ceAdminBtn')){const n=b.cloneNode(true);n.id='ceAdminBtn';n.innerHTML='<span>🛡️</span> Super Admins';n.onclick=openAdmins;b.parentElement.insertBefore(n,b)}});const qa=[...document.querySelectorAll('button')].find(b=>/customize app/i.test(b.textContent));if(qa&&!document.getElementById('ceQuickAdmin')){const n=qa.cloneNode(true);n.id='ceQuickAdmin';n.textContent='🛡️ Super Admins';n.onclick=openAdmins;qa.parentElement.appendChild(n)}};
    window.credenceOpenSuperAdmins=openAdmins;addButton();
  }
  load();
})();
