(function(){
const PRIMARY_UID='aBYdbFwbsTUbpmYtoNurxyu3Roj2';
let fsPromise;
const fs=()=>fsPromise||(fsPromise=import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js'));
const fb=()=>window.credenceFirebase;
const toast=m=>{let t=document.getElementById('ceFixToast');if(!t){t=document.createElement('div');t.id='ceFixToast';t.style='position:fixed;right:18px;bottom:82px;background:#17352a;color:#fff;padding:12px 15px;border-radius:10px;z-index:99999;font-weight:700';document.body.appendChild(t)}t.textContent=m;t.style.display='block';clearTimeout(t._x);t._x=setTimeout(()=>t.style.display='none',2600)};
async function isSuper(){const f=fb(),u=f?.auth?.currentUser;if(!f||!u)return false;if(u.uid===PRIMARY_UID)return true;try{const x=await fs(),s=await x.getDoc(x.doc(f.db,'superAdmins',u.uid));return s.exists()&&s.data().active===true}catch(e){return false}}
async function setActive(col,id,next,label){if(!(await isSuper()))return toast('Super Admin permission required.');try{const x=await fs(),f=fb();await x.updateDoc(x.doc(f.db,col,id),{active:!!next,updatedAt:x.serverTimestamp()});toast(label+(next?' enabled.':' disabled.'));if(col==='students')window.credenceOpenStudents?.();if(col==='teachers')window.credenceOpenTeachers?.();if(col==='superAdmins')window.credenceOpenSuperAdmins?.()}catch(e){toast('Could not update '+label.toLowerCase()+': '+(e.message||e))}}
async function toggleAdmin(id){const x=await fs(),f=fb(),s=await x.getDoc(x.doc(f.db,'superAdmins',id));if(!s.exists())return toast('Admin record not found.');await setActive('superAdmins',id,s.data().active!==true,'Super Admin')}
async function toggleStudent(id){const x=(window.credenceStudents||[]).find(s=>s.id===id);if(!x)return;await setActive('students',id,x.active===false,'Student')}
async function toggleTeacher(id){const x=(window.credenceTeachers||[]).find(s=>s.id===id);if(!x)return;await setActive('teachers',id,x.active===false,'Teacher')}
async function removeStudent(id,name){if(!(await isSuper()))return toast('Super Admin permission required.');if(!confirm('Remove '+(name||'this student')+' permanently?'))return;try{const x=await fs(),f=fb();await x.deleteDoc(x.doc(f.db,'students',id));toast('Student removed.');window.credenceOpenStudents?.()}catch(e){toast('Could not remove student: '+e.message)}}
async function removeTeacher(id,name){if(!(await isSuper()))return toast('Super Admin permission required.');if(!confirm('Remove '+(name||'this teacher')+' permanently?'))return;try{const x=await fs(),f=fb();await x.deleteDoc(x.doc(f.db,'teachers',id));toast('Teacher removed.');window.credenceOpenTeachers?.()}catch(e){toast('Could not remove teacher: '+e.message)}}
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function actionButton(id,disabled,label,kind){return '<button class="btn '+(disabled?'alt':'danger')+'" data-ce-'+kind+'="'+esc(id)+'">'+(disabled?'Enable':'Disable')+'</button>'}
function patchAdminButtons(){const list=document.getElementById('ceList');if(!list)return;list.querySelectorAll('[data-admin]').forEach(b=>{const row=b.closest('.row'),disabled=!!row?.querySelector('.badge.cancel');b.textContent=disabled?'Enable':'Disable';b.className='btn '+(disabled?'alt':'danger');b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleAdmin(b.dataset.admin)}})}
function patchStudentButtons(){const body=document.getElementById('ceStudentRows');if(!body)return;body.querySelectorAll('tr').forEach(r=>{const b=r.querySelector('[data-toggle-student]');if(!b)return;const disabled=!!r.querySelector('.badge.cancel');b.textContent=disabled?'Enable':'Disable';b.className='btn '+(disabled?'alt':'danger');b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleStudent(b.dataset.toggleStudent)};const rm=r.querySelector('[data-remove-student]');if(rm)rm.onclick=e=>{e.preventDefault();e.stopPropagation();removeStudent(rm.dataset.removeStudent,r.querySelector('td b')?.textContent||'this student')}})}
function patchTeacherButtons(){const body=document.getElementById('ceTeacherRows');if(!body)return;body.querySelectorAll('tr').forEach(r=>{const b=r.querySelector('[data-toggle-teacher]');if(!b)return;const disabled=!!r.querySelector('.badge.cancel');b.textContent=disabled?'Enable':'Disable';b.className='btn '+(disabled?'alt':'danger');b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleTeacher(b.dataset.toggleTeacher)};const rm=r.querySelector('[data-remove-teacher]');if(rm)rm.onclick=e=>{e.preventDefault();e.stopPropagation();removeTeacher(rm.dataset.removeTeacher,r.querySelector('td b')?.textContent||'this teacher')}})}
function patch(){patchAdminButtons();patchStudentButtons();patchTeacherButtons();wireBottomNav()}
function wireBottomNav(){const bar=document.querySelector('.mobilebar');if(!bar)return;const wanted=[['🏠','Home'],['👨‍🎓','Students'],['👩‍🏫','Teachers'],['📚','Classes'],['💳','Fees'],['⚙️','Customize']];const old=[...bar.querySelectorAll('button')];if(bar.dataset.ceBottom==='1')return;bar.dataset.ceBottom='1';bar.innerHTML=wanted.map((x,i)=>'<button type="button" data-ce-nav="'+x[1]+'"><span>'+x[0]+'</span><br>'+x[1]+'</button>').join('');bar.querySelectorAll('[data-ce-nav]').forEach(b=>{const n=b.dataset.ceNav;if(n==='Students')b.onclick=()=>window.credenceOpenStudents?.();else if(n==='Teachers')b.onclick=()=>window.credenceOpenTeachers?.();else if(n==='Customize'){b.onclick=()=>{const q=[...document.querySelectorAll('button')].find(x=>/^customize app$/i.test((x.textContent||'').trim()));if(q)q.click()}}else if(n==='Home')b.onclick=()=>{const q=document.querySelector('.view');if(q){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));q.classList.add('active')}}else{const q=[...old].find(x=>new RegExp('^'+n+'$','i').test((x.textContent||'').trim()));if(q)b.onclick=()=>q.click()}})}
async function openTeachers(){if(!(await isSuper()))return toast('Super Admin permission required.');let v=document.getElementById('ceTeacherView');if(v){v.style.display='block';return renderTeachers()}v=document.createElement('div');v.id='ceTeacherView';v.style='position:fixed;inset:0;background:#f3f7f4;z-index:495;overflow:auto;padding:18px';v.innerHTML='<div style="max-width:1100px;margin:auto"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px"><div><h1 style="margin:0;color:#17352a">Teacher Management</h1><div style="color:#718078;margin-top:4px">Manage teachers and their active status.</div></div><button id="ceTeacherClose" class="btn">Back</button></div><div class="card" style="margin-bottom:16px"><h2>Add Teacher</h2><div class="formgrid"><div class="field"><label>Full name</label><input id="ceTeacherName" placeholder="Teacher name"></div><div class="field"><label>Subject</label><input id="ceTeacherSubject" placeholder="Subject"></div><div class="field"><label>Phone</label><input id="ceTeacherPhone" placeholder="Phone"></div><div class="field"><label>Email</label><input id="ceTeacherEmail" type="email" placeholder="teacher@example.com"></div></div><button id="ceTeacherSave" class="btn" style="margin-top:14px">+ Add Teacher</button><div id="ceTeacherMsg" class="muted" style="margin-top:10px"></div></div><div class="card"><h2>Teachers</h2><div class="tablewrap"><table class="table"><thead><tr><th>Name</th><th>Subject</th><th>Phone</th><th>Email</th><th>Status</th><th>Actions</th></tr></thead><tbody id="ceTeacherRows"><tr><td colspan="6">Loading...</td></tr></tbody></table></div></div></div>';document.body.appendChild(v);document.getElementById('ceTeacherClose').onclick=()=>v.remove();document.getElementById('ceTeacherSave').onclick=saveTeacher;renderTeachers()}
async function renderTeachers(){const body=document.getElementById('ceTeacherRows');if(!body)return;try{const x=await fs(),f=fb(),snap=await x.getDocs(x.collection(f.db,'teachers'));window.credenceTeachers=[];snap.forEach(s=>window.credenceTeachers.push({id:s.id,...s.data()}));if(!window.credenceTeachers.length){body.innerHTML='<tr><td colspan="6" class="muted">No teachers yet.</td></tr>';return}body.innerHTML=window.credenceTeachers.map(t=>{const d=t.active===false;return '<tr><td><b>'+esc(t.name||'')+'</b></td><td>'+esc(t.subject||'')+'</td><td>'+esc(t.phone||'')+'</td><td>'+esc(t.email||'')+'</td><td><span class="badge '+(d?'cancel':'')+'">'+(d?'Disabled':'Active')+'</span></td><td><div class="actions">'+actionButton(t.id,d,'Teacher','toggle-teacher')+'<button class="btn danger" data-remove-teacher="'+esc(t.id)+'">Remove</button></div></td></tr>'}).join('');patchTeacherButtons()}catch(e){body.innerHTML='<tr><td colspan="6">Could not load teachers: '+esc(e.message)+'</td></tr>'}}
async function saveTeacher(){const m=document.getElementById('ceTeacherMsg'),data={name:document.getElementById('ceTeacherName').value.trim(),subject:document.getElementById('ceTeacherSubject').value.trim(),phone:document.getElementById('ceTeacherPhone').value.trim(),email:document.getElementById('ceTeacherEmail').value.trim().toLowerCase(),active:true};if(!data.name||!data.subject||!data.phone||!data.email)return m.textContent='Please fill all teacher fields.';if(!(await isSuper()))return m.textContent='Not authorized.';try{const x=await fs(),f=fb();await x.addDoc(x.collection(f.db,'teachers'),{...data,createdAt:x.serverTimestamp(),updatedAt:x.serverTimestamp(),createdBy:f.auth.currentUser.uid});m.textContent='Teacher added successfully.';['ceTeacherName','ceTeacherSubject','ceTeacherPhone','ceTeacherEmail'].forEach(id=>document.getElementById(id).value='');renderTeachers()}catch(e){m.textContent=e.code?e.code+': '+e.message:e.message}}
window.credenceOpenTeachers=openTeachers;
window.credenceOpenSuperAdmins=window.credenceOpenSuperAdmins||null;
window.credenceOpenStudents=window.credenceOpenStudents||null;
patch();new MutationObserver(patch).observe(document.body,{childList:true,subtree:true,characterData:true});
})();