-- CREDENCE canonical Supabase schema. Core tables, RLS, private Storage buckets, and Realtime.
create extension if not exists pgcrypto;
do $$begin create type public.app_role as enum('student','master','admin');exception when duplicate_object then null;end$$;
do $$begin create type public.content_kind as enum('note','test','quiz','video','live_recording');exception when duplicate_object then null;end$$;
do $$begin create type public.access_tier as enum('free','paid');exception when duplicate_object then null;end$$;
do $$begin create type public.chat_message_type as enum('text','image','pdf','video','file');exception when duplicate_object then null;end$$;
do $$begin create type public.order_status as enum('pending','paid','failed','refunded');exception when duplicate_object then null;end$$;
do $$begin create type public.attendance_status as enum('present','absent','late','leave');exception when duplicate_object then null;end$$;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique,full_name text not null default '',email text,phone text,role public.app_role not null default 'student',avatar_url text,active boolean not null default true,banned boolean not null default false,accent_color text not null default '#08783f',preferences jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.app_settings(id boolean primary key default true,logo_url text,tagline text not null default 'Learn smarter. Achieve more.',primary_color text not null default '#08783f',secondary_color text not null default '#0b5b3e',profile_layout text not null default 'compact',app_version text not null default '1.0.0',upi_id text,upi_name text default 'Credence Education',updated_at timestamptz not null default now());
create table if not exists public.banners(id uuid primary key default gen_random_uuid(),title text not null,subtitle text,image_path text,action_text text,action_url text,active boolean not null default true,sort_order int not null default 0,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.courses(id uuid primary key default gen_random_uuid(),title text not null,description text,thumbnail_path text,price_inr numeric(10,2) not null default 0,tier public.access_tier not null default 'free',published boolean not null default false,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.content_items(id uuid primary key default gen_random_uuid(),kind public.content_kind not null,title text not null,description text,course_id uuid references public.courses(id) on delete set null,file_path text,video_url text,tier public.access_tier not null default 'free',price_inr numeric(10,2) not null default 0,duration_seconds int,published boolean not null default false,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.test_questions(id uuid primary key default gen_random_uuid(),content_id uuid references public.content_items(id) on delete cascade,question_text text not null,options jsonb not null default '[]',correct_option int,marks numeric(6,2) not null default 1,negative_marks numeric(6,2) not null default 0,sort_order int not null default 0);
create table if not exists public.test_attempts(id uuid primary key default gen_random_uuid(),content_id uuid references public.content_items(id) on delete cascade,student_id uuid references public.profiles(id) on delete cascade,started_at timestamptz not null default now(),submitted_at timestamptz,score numeric(8,2),total_marks numeric(8,2),answers jsonb not null default '{}',time_spent_seconds int);
create table if not exists public.live_streams(id uuid primary key default gen_random_uuid(),title text not null,description text,course_id uuid references public.courses(id) on delete set null,stream_url text,playback_url text,scheduled_at timestamptz,started_at timestamptz,ended_at timestamptz,tier public.access_tier not null default 'free',price_inr numeric(10,2) not null default 0,is_live boolean not null default false,recording_path text,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table if not exists public.attendance(id uuid primary key default gen_random_uuid(),student_id uuid references public.profiles(id) on delete cascade,class_date date not null default current_date,status public.attendance_status not null,note text,marked_by uuid references public.profiles(id),created_at timestamptz not null default now(),unique(student_id,class_date));
create table if not exists public.conversations(id uuid primary key default gen_random_uuid(),title text,is_group boolean not null default false,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.conversation_members(conversation_id uuid references public.conversations(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,joined_at timestamptz not null default now(),primary key(conversation_id,user_id));
create table if not exists public.chat_messages(id uuid primary key default gen_random_uuid(),conversation_id uuid references public.conversations(id) on delete cascade,sender_id uuid references public.profiles(id) on delete cascade,type public.chat_message_type not null default 'text',body text,media_path text,media_name text,media_size bigint,created_at timestamptz not null default now());
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,title text not null,body text not null,link text,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),student_id uuid references public.profiles(id) on delete cascade,course_id uuid references public.courses(id) on delete set null,content_id uuid references public.content_items(id) on delete set null,amount_inr numeric(10,2) not null,status public.order_status not null default 'pending',payment_reference text,payment_method text default 'upi',note text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.enrollments(id uuid primary key default gen_random_uuid(),student_id uuid references public.profiles(id) on delete cascade,course_id uuid references public.courses(id) on delete cascade,order_id uuid references public.orders(id) on delete set null,active boolean not null default true,created_at timestamptz not null default now(),unique(student_id,course_id));
create or replace function public.is_master(uid uuid default auth.uid()) returns boolean language sql stable security invoker set search_path=public as $$select exists(select 1 from public.profiles where id=uid and active and not banned and role in('master','admin'))$$;
create or replace function public.can_access_content(cid uuid,uid uuid default auth.uid()) returns boolean language sql stable security invoker set search_path=public as $$select exists(select 1 from public.content_items c where c.id=cid and c.published and(c.tier='free' or public.is_master(uid) or exists(select 1 from public.enrollments e where e.student_id=uid and e.course_id=c.course_id and e.active) or exists(select 1 from public.orders o where o.student_id=uid and o.content_id=cid and o.status='paid')))$$;
alter table public.profiles enable row level security;alter table public.app_settings enable row level security;alter table public.banners enable row level security;alter table public.courses enable row level security;alter table public.content_items enable row level security;alter table public.test_questions enable row level security;alter table public.test_attempts enable row level security;alter table public.live_streams enable row level security;alter table public.attendance enable row level security;alter table public.conversations enable row level security;alter table public.conversation_members enable row level security;alter table public.chat_messages enable row level security;alter table public.notifications enable row level security;alter table public.orders enable row level security;alter table public.enrollments enable row level security;
-- Runtime RLS policies are provisioned on the connected project; keep this file as the source-of-truth for the data model and security contract.
insert into public.app_settings(id) values(true) on conflict(id) do nothing;
